IF EXISTS(SELECT * FROM sys.databases WHERE name='WEBNOTE')
BEGIN
	DROP DATABASE WEBNOTE
END
CREATE DATABASE WEBNOTE
GO
USE WEBNOTE
GO

CREATE TABLE DANGNHAP (
  MA INT IDENTITY(1, 1) NOT NULL,
  TENDANGNHAP VARCHAR(50) UNIQUE,
  MATKHAU VARCHAR(MAX),
  CONSTRAINT PK_DN PRIMARY KEY (MA)
)

CREATE TABLE THONGTINNGUOIDUNG ( -- thông tin người dùng
  MA INT IDENTITY(1, 1) NOT NULL,
  TENNGUOIDUNG NVARCHAR(50),
  EMAIL VARCHAR(50),
  SDT VARCHAR(12),
  AVT VARCHAR(MAX),
  BACKGROUND VARCHAR(MAX),
  MADN INT,
  CONSTRAINT PK_TTND PRIMARY KEY (MA),
  CONSTRAINT FK_TTND_DN FOREIGN KEY (MADN) REFERENCES DANGNHAP(MA)
)

CREATE TABLE NOTE (
  MA INT IDENTITY(1, 1) NOT NULL, --==
  TITLE NVARCHAR(MAX),
  TINHTRANG VARCHAR(10), -- Remove to bin recycle, Storage or null (default null)
  NGAYTAO DATE, -- default getdate()
  NGAYCN DATE, -- ngày cập nhật getdate()
  MADN INT, -- của người dùng nào
  CONSTRAINT PK_NOTE PRIMARY KEY (MA),
  CONSTRAINT FK_NOTE_DN FOREIGN KEY (MADN) REFERENCES DANGNHAP(MA)
)


CREATE TABLE CONTENT_PLAINTEXT (
  MA INT IDENTITY(1, 1) NOT NULL,
  NOIDUNG NVARCHAR(MAX),
  MANOTE INT UNIQUE,
  CONSTRAINT PK_CP PRIMARY KEY (MA),
  CONSTRAINT FK_CP_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
)

-- CREATE TABLE CONTENT_LISTCHECK (
--   MA INT IDENTITY(1, 1) NOT NULL,
--   NOIDUNG NTEXT,
--   ISCHECK BIT, -- 0, 1
--   MANOTE INT,
--   CONSTRAINT PK_CLC PRIMARY KEY (MA),
--   CONSTRAINT FK_CLC_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
-- )

GO
---------------------------------------------------------------------------------
-- StoreProc
CREATE PROC spAddNote
@Title NVARCHAR(MAX),
@CodeDN INT,
@ContentCard NVARCHAR(MAX),
@NewId INT OUTPUT
AS
BEGIN
	INSERT NOTE(TITLE, MADN) VALUES(@Title, @CodeDN)

	SELECT @NewId = SCOPE_IDENTITY()

	INSERT CONTENT_PLAINTEXT(NOIDUNG, MANOTE) VALUES(@ContentCard, @NewId)
END
GO
---------------------------------------------------------------------------------
-- trigger
CREATE TRIGGER UD_NOTE ON CONTENT_PLAINTEXT
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @codeCard INT
	SELECT @codeCard=MANOTE FROM inserted

	UPDATE NOTE
	SET NGAYCN = GETDATE()
	WHERE MA=@codeCard

END
GO
---------------------------------------------------------------------------------
--tạo ràng buộc
ALTER TABLE THONGTINNGUOIDUNG
ADD CONSTRAINT DF_BK DEFAULT '' FOR BACKGROUND,
	CONSTRAINT DF_AVT DEFAULT 'avtDefault.png' FOR AVT

ALTER TABLE NOTE
ADD CONSTRAINT DF_NGAYTAO DEFAULT GETDATE() FOR NGAYTAO,
    CONSTRAINT DF_TT DEFAULT NULL FOR TINHTRANG

-- ALTER TABLE CONTENT_LISTCHECK
-- ADD CONSTRAINT DF_ISCHECK DEFAULT 0 FOR ISCHECK
