IF EXISTS(SELECT * FROM sys.databases WHERE name='WEBNOTE')
BEGIN
	DROP DATABASE WEBNOTE
END
CREATE DATABASE WEBNOTE
GO
USE WEBNOTE
GO

CREATE TABLE DANGNHAP (
  MA INT IDENTITY(1, 1) NOT NULL,
  TENDANGNHAP VARCHAR(50) UNIQUE,
  MATKHAU VARCHAR(MAX),
  CONSTRAINT PK_DN PRIMARY KEY (MA)
)

CREATE TABLE THONGTINNGUOIDUNG ( -- thông tin người dùng
  MA INT IDENTITY(1, 1) NOT NULL,
  TENNGUOIDUNG NVARCHAR(50),
  EMAIL VARCHAR(50),
  SDT VARCHAR(12),
  AVT VARCHAR(MAX),
  BACKGROUND VARCHAR(MAX),
  MADN INT,
  CONSTRAINT PK_TTND PRIMARY KEY (MA),
  CONSTRAINT FK_TTND_DN FOREIGN KEY (MADN) REFERENCES DANGNHAP(MA)
)

CREATE TABLE NOTE (
  MA INT IDENTITY(1, 1) NOT NULL, --==
  TITLE NVARCHAR(50),
  TINHTRANG VARCHAR(10), -- Remove, Store or null (default null)
  NGAYTAO DATE, -- default getdate()
  NGAYCN DATE, -- ngày cập nhật
  TENDANGNHAP VARCHAR(50), -- của người dùng nào
  CONSTRAINT PK_NOTE PRIMARY KEY (MA),
  CONSTRAINT FK_NOTE_DN FOREIGN KEY (TENDANGNHAP) REFERENCES DANGNHAP(TENDANGNHAP)
)


CREATE TABLE CONTENT_PLAINTEXT (
  MA INT IDENTITY(1, 1) NOT NULL,
  NOIDUNG NTEXT,
  MANOTE INT UNIQUE,
  CONSTRAINT PK_CP PRIMARY KEY (MA),
  CONSTRAINT FK_CP_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
)

CREATE TABLE CONTENT_LISTCHECK (
  MA INT IDENTITY(1, 1) NOT NULL,
  NOIDUNG NTEXT,
  ISCHECK BIT, -- 0, 1
  MANOTE INT,
  CONSTRAINT PK_CLC PRIMARY KEY (MA),
  CONSTRAINT FK_CLC_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
)

GO
---------------------------------------------------------------------------------
--tạo ràng buộc
ALTER TABLE THONGTINNGUOIDUNG
ADD CONSTRAINT DF_BK DEFAULT '' FOR BACKGROUND,
	CONSTRAINT DF_AVT DEFAULT 'avtDefault.png' FOR AVT

ALTER TABLE NOTE
ADD CONSTRAINT DF_NGAYTAO DEFAULT GETDATE() FOR NGAYTAO,
    CONSTRAINT DF_TT DEFAULT NULL FOR TINHTRANG

ALTER TABLE CONTENT_LISTCHECK
ADD CONSTRAINT DF_ISCHECK DEFAULT 0 FOR ISCHECK
