IF EXISTS(SELECT * FROM sys.databases WHERE name='WEBNOTE')
BEGIN
	DROP DATABASE WEBNOTE
END
CREATE DATABASE WEBNOTE
GO
USE WEBNOTE
GO

CREATE TABLE DANGNHAP (
  MA INT IDENTITY(1, 1) NOT NULL,
  TENDANGNHAP VARCHAR(50) UNIQUE,
  MATKHAU VARCHAR(50),
  CONSTRAINT PK_DN PRIMARY KEY (MA)
)

CREATE TABLE THONGTINNGUOIDUNG ( -- thông tin người dùng
  MA INT IDENTITY(1, 1) NOT NULL,
  TENNGUOIDUNG NVARCHAR(50),
  EMAIL VARCHAR(50),
  SDT VARCHAR(12),
  AVT VARCHAR(MAX),
  TENDANGNHAP VARCHAR(50),
  CONSTRAINT PK_TTND PRIMARY KEY (MA),
  CONSTRAINT FK_TTND_DN FOREIGN KEY (TENDANGNHAP) REFERENCES DANGNHAP(TENDANGNHAP)
)

CREATE TABLE NOTE (
  MA INT IDENTITY(1, 1) NOT NULL, --==
  TITLE NVARCHAR(50),
  BACKGROUND VARCHAR(8), -- màu nền (default #000000 == black)
  TINHTRANG VARCHAR(10), -- Remove, Save or null (default null)
  NGAYTAO DATE, -- default getdate()
  NGAYCN DATE, -- ngày cập nhật
  TENDANGNHAP VARCHAR(50), -- của người dùng nào
  CONSTRAINT PK_NOTE PRIMARY KEY (MA),
  CONSTRAINT FK_NOTE_DN FOREIGN KEY (TENDANGNHAP) REFERENCES DANGNHAP(TENDANGNHAP)
)

CREATE TABLE IMG (
  MA INT IDENTITY(1, 1) NOT NULL,
  IMAGENAME VARCHAR(50), -- tên ảnh có thể trùng tùy thuộc vào người dùng lưu
  MANOTE INT, -- thuộc note nào
  CONSTRAINT PK_IMG PRIMARY KEY (MA),
  CONSTRAINT FK_IMG_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
)

CREATE TABLE CONTENT_PLAINTEXT (
  MA INT IDENTITY(1, 1) NOT NULL,
  NOIDUNG NTEXT,
  MANOTE INT,
  CONSTRAINT PK_CP PRIMARY KEY (MA),
  CONSTRAINT FK_CP_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
)

CREATE TABLE CONTENT_LISTCHECK (
  MA INT IDENTITY(1, 1) NOT NULL,
  NOIDUNG NTEXT,
  ISCHECK BIT, -- 0, 1
  MANOTE INT,
  CONSTRAINT PK_CLC PRIMARY KEY (MA),
  CONSTRAINT FK_CLC_NOTE FOREIGN KEY (MANOTE) REFERENCES NOTE(MA) ON DELETE CASCADE
)

GO
---------------------------------------------------------------------------------
--tạo ràng buộc
ALTER TABLE NOTE
ADD CONSTRAINT DF_NGAYTAO DEFAULT GETDATE() FOR NGAYTAO,
    CONSTRAINT DF_TT DEFAULT NULL FOR TINHTRANG,
    CONSTRAINT DF_BG DEFAULT '#000000' FOR BACKGROUND,
    CONSTRAINT CK_BG CHECK (BACKGROUND IN('#000000', '#FF0000', '#00FF00'))

ALTER TABLE CONTENT_LISTCHECK
ADD CONSTRAINT DF_ISCHECK DEFAULT 0 FOR ISCHECK
